// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-invoices.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-invoices.ts
var toInvoiceSummary = (row) => ({
  id: String(row.id),
  invoice_number: String(row.invoice_number),
  status: String(row.status),
  currency: String(row.currency),
  total_amount: Number(row.total_amount),
  issue_date: String(row.issue_date),
  due_date: String(row.due_date),
  client_name: row.client_details && typeof row.client_details === "object" ? String(row.client_details.name ?? "") : ""
});
var list_invoices_default = defineTool({
  name: "list_invoices",
  title: "List invoices",
  description: "List the signed-in user's invoices, newest first, optionally filtered by status.",
  inputSchema: {
    status: z.enum(["draft", "pending", "paid", "overdue"]).optional().describe("Only return invoices with this status."),
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of invoices to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("invoices").select("id,invoice_number,status,currency,total_amount,issue_date,due_date,client_details").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const invoices = (data ?? []).map((row) => toInvoiceSummary(row));
    return {
      content: [{ type: "text", text: JSON.stringify(invoices, null, 2) }],
      structuredContent: { invoices }
    };
  }
});

// src/lib/mcp/tools/get-invoice.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var toInvoiceJson = (row) => ({
  id: String(row.id),
  invoice_number: String(row.invoice_number),
  status: String(row.status),
  currency: String(row.currency),
  issue_date: String(row.issue_date),
  due_date: String(row.due_date),
  subtotal: Number(row.subtotal),
  tax_rate: Number(row.tax_rate),
  discount_rate: Number(row.discount_rate),
  total_amount: Number(row.total_amount),
  notes: row.notes ? String(row.notes) : "",
  payment_terms: row.payment_terms ? String(row.payment_terms) : "",
  template: String(row.template),
  client_id: row.client_id ? String(row.client_id) : null,
  client_details: JSON.parse(JSON.stringify(row.client_details ?? {})),
  business_details: JSON.parse(JSON.stringify(row.business_details ?? {})),
  items: (Array.isArray(row.items) ? row.items : []).map((item) => {
    const line = item;
    return {
      description: String(line.description ?? ""),
      quantity: Number(line.quantity ?? 0),
      rate: Number(line.rate ?? 0)
    };
  })
});
var get_invoice_default = defineTool2({
  name: "get_invoice",
  title: "Get invoice",
  description: "Fetch one of the signed-in user's invoices in full, by id or invoice number.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("The invoice id."),
    invoice_number: z2.string().trim().min(1).optional().describe("The invoice number, e.g. INV-001.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, invoice_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !invoice_number) throw new ToolError("Provide either id or invoice_number.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("invoices").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("invoice_number", invoice_number);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError("No matching invoice found.");
    const invoice = toInvoiceJson(data);
    return {
      content: [{ type: "text", text: JSON.stringify(invoice, null, 2) }],
      structuredContent: { invoice }
    };
  }
});

// src/lib/mcp/tools/create-invoice.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var lineItem = z3.object({
  description: z3.string().trim().min(1),
  quantity: z3.number().positive(),
  rate: z3.number().min(0)
});
var create_invoice_default = defineTool3({
  name: "create_invoice",
  title: "Create invoice",
  description: "Create a new invoice for the signed-in user with line items, tax and discount.",
  inputSchema: {
    invoice_number: z3.string().trim().min(1).describe("Invoice number, e.g. INV-001."),
    issue_date: z3.string().describe("Issue date, YYYY-MM-DD."),
    due_date: z3.string().describe("Due date, YYYY-MM-DD."),
    currency: z3.string().trim().length(3).default("USD").describe("3-letter currency code."),
    status: z3.enum(["draft", "pending", "paid", "overdue"]).default("draft"),
    client_name: z3.string().trim().min(1).describe("Client name shown on the invoice."),
    client_company: z3.string().trim().default("").describe("Client company."),
    client_email: z3.string().trim().default("").describe("Client email."),
    client_address: z3.string().trim().default("").describe("Client address."),
    items: z3.array(lineItem).min(1).describe("Line items on the invoice."),
    tax_rate: z3.number().min(0).max(100).default(0).describe("Tax rate as a percentage."),
    discount_rate: z3.number().min(0).max(100).default(0).describe("Discount rate as a percentage."),
    notes: z3.string().trim().default("").describe("Notes shown on the invoice."),
    payment_terms: z3.string().trim().default("").describe("Payment terms text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const taxRate = input.tax_rate ?? 0;
    const discountRate = input.discount_rate ?? 0;
    const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.rate, 0);
    const total = subtotal - subtotal * discountRate / 100 + subtotal * taxRate / 100;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("invoices").insert({
      user_id: ctx.getUserId(),
      invoice_number: input.invoice_number,
      issue_date: input.issue_date,
      due_date: input.due_date,
      currency: input.currency ?? "USD",
      status: input.status ?? "draft",
      client_details: {
        name: input.client_name,
        company: input.client_company ?? "",
        email: input.client_email ?? "",
        address: input.client_address ?? ""
      },
      items: input.items.map((item, index) => ({
        id: `item-${index + 1}`,
        description: item.description,
        quantity: item.quantity,
        rate: item.rate
      })),
      tax_rate: taxRate,
      discount_rate: discountRate,
      notes: input.notes ?? "",
      payment_terms: input.payment_terms ?? "",
      subtotal,
      total_amount: total
    }).select("id,invoice_number,status,currency,subtotal,total_amount,issue_date,due_date").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const invoice = {
      id: String(data.id),
      invoice_number: String(data.invoice_number),
      status: String(data.status),
      currency: String(data.currency),
      subtotal: Number(data.subtotal),
      total_amount: Number(data.total_amount),
      issue_date: String(data.issue_date),
      due_date: String(data.due_date)
    };
    return {
      content: [{ type: "text", text: `Created invoice ${invoice.invoice_number} (${invoice.id}).` }],
      structuredContent: { invoice }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's saved clients, optionally filtered by a name or company search.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Match client name or company."),
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of clients to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id,name,company,email,address,tax_id,created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const clients = (data ?? []).map((row) => ({
      id: String(row.id),
      name: String(row.name),
      company: row.company ? String(row.company) : "",
      email: row.email ? String(row.email) : "",
      address: row.address ? String(row.address) : "",
      tax_id: row.tax_id ? String(row.tax_id) : ""
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(clients, null, 2) }],
      structuredContent: { clients }
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_client_default = defineTool5({
  name: "create_client",
  title: "Create client",
  description: "Save a new client to the signed-in user's client list.",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Client name."),
    company: z5.string().trim().optional().describe("Company name."),
    email: z5.string().trim().email().optional().describe("Client email."),
    address: z5.string().trim().optional().describe("Billing address."),
    tax_id: z5.string().trim().optional().describe("Tax or VAT identifier.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clients").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      company: input.company ?? null,
      email: input.email ?? null,
      address: input.address ?? null,
      tax_id: input.tax_id ?? null
    }).select("id,name,company,email,address,tax_id").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const client = {
      id: String(data.id),
      name: String(data.name),
      company: data.company ? String(data.company) : "",
      email: data.email ? String(data.email) : "",
      address: data.address ? String(data.address) : "",
      tax_id: data.tax_id ? String(data.tax_id) : ""
    };
    return {
      content: [{ type: "text", text: `Saved client ${client.name} (${client.id}).` }],
      structuredContent: { client }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dzftjiqegyphqyfdbidm";
var mcp_default = defineMcp({
  name: "this-invoicing",
  title: "THIS Invoicing",
  version: "0.1.0",
  instructions: "Tools for the Invofy invoicing app. Read and create invoices and clients for the signed-in user. Use `list_invoices` to browse, `get_invoice` for full detail, `create_invoice` to draft a new invoice, and `list_clients` / `create_client` to manage the client list.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_invoices_default, get_invoice_default, create_invoice_default, list_clients_default, create_client_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
